name: plv
channels:
  - conda-forge
dependencies:
  - python>=3.10, <3.11.5
  - pip
  - numpy=1.24.1, <2x
  - pandas=1.5.2, <2
  - statsmodels=0.14
  - matplotlib=3.6.2, <4
  - mpl-interactions=0.22.0
  - ipywidgets=7.7.0
  - ipympl=0.9.1
  - jupyter=1.0.0
  # In general, notebook should be smaller than 7 so that jupyter_contrib_nbextensions and rise can be used
  - notebook=6.5.5, <7
  - traitlets=5.9.0
  - mlflow=2.7.1 # needs a lot of dependencies
  - pip:
    - rise==5.7.1  # Dependencies not available on conda-forge
    - -e .